- libraries/provider_lvm_logical_volume.rb
- libraries/provider_lvm_volume_group.rb
Upgrading to Chef12 has left our LVM HWRP's unusable. It seems that the problem is that Chef12 no longer includes the Recipe DSL for heavyweight providers. I've simply added the include where required. Tested successfully on Chef12, but not Chef11... I suspect it should be fine though.
We will be switching to a fork containing this change in the meantime as this hampers our ability to bootstrap new hosts. On another note, if this (or other related) fix is held up for one reason or another, we should update the Readme to reflect Chef12 incompatibility.
Directly related to/alternate approach for:
https://github.com/opscode-cookbooks/lvm/issues/44
https://github.com/opscode-cookbooks/lvm/issues/42
https://github.com/opscode-cookbooks/lvm/pull/41
> Include Chef::DSL::Recipe in HWRPs which require it (and fix Chef12)

- recipes/default.rb
the lvmetad service is required by default in RHEL7 but is not automatically started.   This patch enables and starts the service on RHEL7.
fixes: #43
> Start+Enable the lvmetad service on RHEL7

- metadata.rb
Chef 12 methods used in the metadata are incompatible with chef 11.  Checked for response.
> Make the metadata compatible with chef 11.

- attributes/default.rb
- spec/default_spec.rb
To support more versions of LVM added in more recent versions of `di-ruby-lvm-attrib`.
> Bump version of di-ruby-lvm-attrib

- recipes/default.rb
Compile time being true causes issues in environments where systems do not have direct internet access and the proxies are set up in the run list.  
I have tested that setting compile time to false avoid such issues and the existing suite of tests continues to run.
> Set compilte ttime to false for the chef_gem resources.

- libraries/resource_lvm_logical_volume.rb
While the actual problem for #71 was caused by not specifying an absolute path for the mount point location, it tickled a latent bug in the validation logic where, if the mount point was specified as a string, and the string validation failed, it would then attempt to treat the string like a hash, which did not work. This change makes it so that only strings are checked as strings should be checked, and only hashes are checked as hashes should be checked.
> Fix Issue 71

- libraries/resource_lvm_logical_volume.rb
2.2.3 :009 > case "something".class
2.2.3 :010?>   when String
2.2.3 :011?>   puts 'String!'
2.2.3 :012?>   end
=> nil
2.2.3 :013 > case "something"
2.2.3 :014?>   when String
2.2.3 :015?>   puts 'String!'
2.2.3 :016?>   end
String!
> Bugfix: case uses === not == so "case value" not "case value.class"

- test/fixtures/cookbooks/test/recipes/create.rb
- test/fixtures/cookbooks/test/recipes/resize.rb
Fixes https://github.com/chef-cookbooks/lvm/issues/86 which is caused by the lvm gems not being installed before the tests use them.
> Include lvm recipe so lvm gems are installed for tests

- attributes/default.rb
- spec/default_spec.rb
This fixes issues with di-ruby-lvm-attrib gem not having the correct version stored for latest lvm updates.
> fix di-ruby-lvm-attrib attribute version

- README.md
- libraries/provider_lvm_volume_group.rb
- libraries/resource_lvm_volume_group.rb
As mentioned in https://github.com/chef-cookbooks/lvm/issues/45 -  RHEL7's lvm command now interactively prompts users with a `WARNING: ext3 signature detected on /dev/xvdb at offset 1080. Wipe it? [y/n]` message. 
This is particularly painful for AWS users, where ephemeral volumes come preformatted with ext3.
This PR adds a `wipe_signatures` option to `lvm_volume_group` that looks like so:
```ruby
lvm_volume_group 'opscode' do
physical_volumes [ '/dev/xvdb', '/dev/xvdc' ]
wipe_signatures true
end
```
This feature comes with a big CAVEAT EMPTOR that it will wipe out the physical volumes provided to `lvm_volume_group` -  but this is the behavior you already get with lvm on RHEL <= 6 and all of the Ubuntu so really the point here is to have platform parity for RHEL7.
> Add a wipe_signatures option to LVM volume group

- .kitchen.yml
- attributes/default.rb
This change updates di-ruby-lvm-attrib to the latest version
#98 
Kitchen tests are failing on ubuntu-1604 but this was already happening before this change. I have made a PR for a fix, https://github.com/gregsymons/di-ruby-lvm-attrib/pull/46
> Update di-ruby-lvm-attrib #98

- libraries/base_resource_logical_volume.rb
- libraries/resource_lvm_thin_pool.rb
Because we are including dsl:recipe in the resource namespace other cookbooks using a custom resource are picking it up and breaking.
None known.
Kitchen tests are failing on ubuntu-1604, once di-ruby-lvm-attrib's next version is released we should see these clear.
Kitchen tests are also failing on centos-511. It appears the line that we are using to resize the loop device for the test is incorrect which is causing the test to fail. The cookbook converges but the test will fail checking extents.
> Moving include dsl:recipe out of resource namespace

- attributes/default.rb
Update to `di-ruby-lvm-attrib` 0.0.27. 0.0.26 is lacking the metadata needed on Ubuntu 16.04.
#105
thin tests are failing due to a different issue. non-thin tests pass.
> Update to di-ruby-lvm-attrib 0.0.27

- README.md
- libraries/base_resource_logical_volume.rb
- libraries/provider_lvm_logical_volume.rb
- libraries/provider_lvm_physical_volume.rb
- libraries/resource_lvm_logical_volume.rb
- libraries/resource_lvm_physical_volume.rb
- libraries/resource_lvm_volume_group.rb
The adds the "yes_flag" aka the "wipe_signatures" attribute also to PVs and LVs.
I have an environment were existing LV metadata is present and without the "--yes" flag the LV would not be created and the "lvcreate" would hang forever.
- [ x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [not needed/possible ] New functionality includes testing.
- [x ] New functionality has been documented in the README if applicable
- [x ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>
> "yes_flag" aka the "wipe_signatures" attribute for PVs and LVs

- libraries/provider_lvm_logical_volume.rb
Signed-off-by: Jeremy J. Miller <jm@chef.io>
Adding in the `Chef::DSL::PlatformIntrospection` namespace to allow `platform_family?` to work.
This change fixes: #115
```
================================================================================
Error executing action `create` on resource 'lvm_logical_volume[volume]'
================================================================================
NoMethodError
-------------
No resource or method named `platform_family?' for `Chef::Provider::LvmLogicalVolume ""'
Cookbook Trace:
---------------
/tmp/kitchen/cache/cookbooks/lvm/libraries/provider_lvm_logical_volume.rb:221:in `install_filesystem_deps'
/tmp/kitchen/cache/cookbooks/lvm/libraries/provider_lvm_logical_volume.rb:47:in `action_create'`
```
> add platformintrospection dsl

- .kitchen.yml
- libraries/lvm.rb
Solves the following deprecation notice in 4.0.1
```
Deprecated features used!
Cloning resource attributes for chef_gem[di-ruby-lvm-attrib] from prior resource (CHEF-3694)
Previous chef_gem[di-ruby-lvm-attrib]: /tmp/kitchen/cache/cookbooks/lvm/libraries/lvm.rb:24:in `require_lvm_gems'
Current  chef_gem[di-ruby-lvm-attrib]: /tmp/kitchen/cache/cookbooks/lvm/libraries/lvm.rb:24:in `require_lvm_gems' at 1 location:
- /tmp/kitchen/cache/cookbooks/lvm/libraries/lvm.rb:24:in `require_lvm_gems'
Cloning resource attributes for chef_gem[di-ruby-lvm] from prior resource (CHEF-3694)
Previous chef_gem[di-ruby-lvm]: /tmp/kitchen/cache/cookbooks/lvm/libraries/lvm.rb:29:in `require_lvm_gems'
Current  chef_gem[di-ruby-lvm]: /tmp/kitchen/cache/cookbooks/lvm/libraries/lvm.rb:29:in `require_lvm_gems' at 1 …
```
> Remove deprecation notice in 4.0.1

- libraries/lvm.rb
Stops the removal of the di-lvm gem after running once.
[List any existing issues this PR resolves]
> Only cleanup gems once

- libraries/lvm.rb
Had the gem remove resources look at node['lvm']['rubysource'] so that it would would speed of the use of the resources
#121 - Removal of old gem fails
> adding source for the air gaped environment use case

- libraries/matchers.rb
Adds missing ChefSpec matchers for the `lvm_thin_pool` and `lvm_thin_volume` LWRPs.
There are currently matchers missing for the `lvm_thin_pool` and `lvm_thin_volume` LWRPs.
> Add missing matchers for lvm thin pools and volumes

- libraries/provider_lvm_logical_volume.rb
Signed-off-by: Stanislav Voroniy <stas@voroniy.com>
Obvious fix
Fix LV creation size when specified in extents
> Obvious fix: for size in extents --extents should be used

- attributes/default.rb
using this cookbook currently fails on 12.21.10. bumping lvm-attrib gem.
> require latest lvm-attrib gem

- libraries/provider_lvm_logical_volume.rb
Description
Found that trying to install packages at compile-time breaks our SUSE runs, as repositories have not yet been configured.
The .run_action here should only necessary for things like Chef gems where the compile would otherwise fail as resources couldn't be defined. It is sufficient to install the package here at runtime.
Issues Resolved
Breaking SUSE run when trying to install packages at compile-time
> Remove end.run_action(:install) as it breaks SUSE runs

- libraries/provider_lvm_logical_volume.rb
- libraries/provider_lvm_volume_group.rb
Signed-off-by: Matthew Newell <matthewtnewell@gmail.com>
This change fixes the `raise` syntax to use the correct call format by removing the second argument. It appears that this was missed when the `Chef::Application.fatal!` calls were converted to use `raise` instead.
This fixes issue #141
> Correct raise syntax to remove the invalid second argument, fixes #141

- README.md
- attributes/default.rb
- libraries/provider_lvm_logical_volume.rb
- libraries/provider_lvm_volume_group.rb
- libraries/resource_lvm_logical_volume.rb
- libraries/resource_lvm_volume_group.rb
- resources/physical_volume.rb
- test/fixtures/cookbooks/test/recipes/create.rb
Signed-off-by: Matthew Newell <matthew.newell@cerner.com>
This change adds the `ignore_skipped_cluster` property to all resources that initialize the LVM object. This allows LVM resources such as VGs, LVs, or PVs to be managed via Chef even if skipped clustered VGs exist. This is set to false by default preserving existing functionality.
#156
> Add support for the ignore_skipped_cluster property, fixes #156

- README.md
- kitchen.yml
- libraries/provider_lvm_thin_pool_meta_data.rb
- libraries/resource_lvm_thin_pool_meta_data.rb
- spec/lvm_test/resize_thin_pool_meta_data_spec.rb
- test/fixtures/cookbooks/test/recipes/create.rb
- test/fixtures/cookbooks/test/recipes/create_thin.rb
- test/fixtures/cookbooks/test/recipes/resize_thin_pool_meta_data.rb
- test/fixtures/cookbooks/test/resources/loop_devices.rb
- test/integration/resize_thin_pool_meta_data/bats/verify_resize_thin_pool_meta_data.bats
Signed-off-by: Vasu1105 <vasundhara.jagdale@msystechnologies.com>
Allows user to extend metadata size for LVM thinpools using LVM cookbook.
Fixes #151
> Fix unable to extend thin pool metadata size.

- CHANGELOG.md
- README.md
- libraries/provider_lvm_logical_volume.rb
- metadata.rb
- spec/lvm_test/resize_spec.rb
- test/fixtures/cookbooks/test/recipes/resize.rb
- test/integration/resize/bats/verify_resize.bats
Signed-off-by: ChrisA.Walker <ChrisA.Walker@target.com>
- Added 'lv_params' to be handled as part of lvm_logical_volume :resize, as it was available only for :create - to resolve GH-159
- Added logic to not pass '--resizefs' if the filesystem is 'RAW'
- Added missing documentation on the hidden option of sending 'lv_params' to the resource for both :create and :resize
https://github.com/chef-cookbooks/lvm/issues/159
https://github.com/chef-cookbooks/lvm/issues/140
https://github.com/chef-cookbooks/lvm/issues/111
https://github.com/chef-cookbooks/lvm/issues/110
> adding logic to handle RAW volumes

- CHANGELOG.md
- attributes/default.rb
- metadata.rb
Signed-off-by: ChrisA.Walker <ChrisA.Walker@target.com>
Updates the chef-ruby-lvm-attrib version to the latest available (0.2.6).
https://github.com/chef-cookbooks/lvm/issues/168
https://github.com/chef-cookbooks/lvm/issues/166
> bumping chef-ruby-lvm-attrib to 0.2.6

- libraries/resource_lvm_thin_volume.rb
Signed-off-by: michael.sgarbossa <msgarbossa@cvs.com>
Add support for the ignore_skipped_cluster property (copied from resource_lvm_logical_volume.rb)
#170
> Add support for the ignore_skipped_cluster property, fixes #170

- CHANGELOG.md
- attributes/default.rb
- metadata.rb
Signed-off-by: Matthew Newell <matthew.newell@cerner.com>
This change increases the chef-ruby-lvm-attrib gem version from 0.2.6 to 0.2.8 to allow for support of later versions of LVM.
Fixes #174
> Bump chef-ruby-lvm-attrib to 0.2.8 from 0.2.6

- README.md
- attributes/default.rb
- libraries/lvm.rb
- test/fixtures/cookbooks/test/recipes/create.rb
- test/fixtures/cookbooks/test/recipes/remove.rb
We've been cleaning up these gems for 3 years now. A new Chef Infra Client install will nuke the directory anyways so there's really no reason to continue this costly cleanup on each Chef Infra Client run.
Signed-off-by: Tim Smith <tsmith@chef.io>
> Remove the legacy gem cleanup logic

- CHANGELOG.md
- attributes/default.rb
- metadata.rb
CHANGELOG.md          | 4 ++++
attributes/default.rb | 2 +-
metadata.rb           | 2 +-
3 files changed, 6 insertions(+), 2 deletions(-)
Signed-off-by: gael martinez <gael.martinez@gmail.com>
Update the attributes gem version from 0.3.1 to 0.3.2 to support RHEL 8.2
Fixes #181
> Update the attributes gem version from 0.3.1 to 0.3.2

- attributes/default.rb
- kitchen.yml
- libraries/base_resource_logical_volume.rb
- spec/default_spec.rb
- spec/lvm_test/create_spec.rb
- spec/lvm_test/create_thin_spec.rb
- spec/lvm_test/remove_spec.rb
- spec/lvm_test/resize_spec.rb
- spec/lvm_test/resize_thin_pool_meta_data_spec.rb
- spec/lvm_test/resize_thin_spec.rb
Updates the chef-ruby-lvm-attrib to 0.3.3 to work with ubuntu 20.04
Updates tests for Ubuntu 20.04
Adds resource_name and provides to the base_resource_logical_volume library for chef 16 support
> Support chef 16 and ubuntu 20.04

- attributes/default.rb
Update to chef-ruby-lvm-attrib 0.3.5 to support latest RHEL7 lvm version.
Support RHEL7 with lvm2-libs-2.02.187-6.el7.rpm
> Chase upstream chef-ruby-lvm-attrib version

- CHANGELOG.md
- attributes/default.rb
- metadata.rb
Signed-off-by: Gael Martinez <gael.martinez@gmail.com>
Update the attribute gem to 5.0.5 to add support for RHEL 8.3
Update the gem pinning to 0.3.6
Fix #198
> Release 5.0.5

- libraries/provider_lvm_thin_pool.rb
I was getting the error:
```
RuntimeError
------------
implicit argument passing of super from method defined by define_method() is not supported. Specify all arguments explicitly.
Cookbook Trace: (most recent call first)
----------------------------------------
/tmp/kitchen/cache/cookbooks/lvm/libraries/provider_lvm_thin_pool.rb:37:in `block in <class:LvmThinPool>'
/tmp/kitchen/cache/cookbooks/lvm/libraries/provider_lvm_volume_group.rb:145:in `block in create_logical_volumes'
/tmp/kitchen/cache/cookbooks/lvm/libraries/provider_lvm_volume_group.rb:143:in `each'
/tmp/kitchen/cache/cookbooks/lvm/libraries/provider_lvm_volume_group.rb:143:in `create_logical_volumes'
/tmp/kitchen/cache/cookbooks/lvm/libraries/provider_lvm_volume_group.rb:61:in `block in <class:LvmVolumeGroup>'
```
This was …
> Need to add explicit parameters for super called from action methods

- CHANGELOG.md
- attributes/default.rb
- metadata.rb
This change updates the chef-ruby-lvm-attrib gem version from 0.3.6 to
0.3.7 to provide support for RHEL/OL 8.4. This has been tested
successfully on the latest RHEL 8.4 ISO.
Signed-off-by: Matthew Newell <matthew.newell@cerner.com>
This change ensures the latest released version of chef-ruby-lvm-attrib gem is used by the lvm cookbook to support RHEL/OL 8.4.
Unit tests succeeded locally, but the GitHub cookbook pipeline is failing with an HTTP error:
```sh
/usr/bin/docker run --name a33c1014a41428d1c4cf7ab2641e346b111ed_9c964a --label 8a33c1 --workdir /github/workspace --rm -e CHEF_LICENSE -e INPUT_GEMS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e …
```
> Update chef-ruby-lvm-attrib to 0.3.7

- CHANGELOG.md
- libraries/provider_lvm_logical_volume.rb
- libraries/provider_lvm_volume_group.rb
- resources/physical_volume.rb
Signed-off-by: Mario Haustein <mario.haustein@hrz.tu-chemnitz.de>
`pvcreate` and `lvcreate` wait for interactive input when the `wipe_signatures` property is not set. This PR changes their behavior to bail out immediately with an error message.
* #217
> [#217] Fix `pvcreate` and `lvcreate` not to wait for interactive input

- CHANGELOG.md
- attributes/default.rb
chef-ruby-lvm-attrib 0.3.10 was yanked from rubygems.out
Obvious fix.
Signed-off-by: ryanwoodsmall <rwoodsmall@gmail.com>
**chef-ruby-lvm-attrib** version 0.3.10 was yanked upstream: https://rubygems.org/gems/chef-ruby-lvm-attrib/versions/0.3.10
This boke a number of builds for cookbooks. Bump the version to the 0.3.11, which is currently latest available.
No issue submitted
- [-] New functionality includes testing.
- [-] New functionality has been documented in the README if applicable.
> Update chef-ruby-lvm-attrib gem to 0.3.11

- CHANGELOG.md
- attributes/default.rb
Update chef-ruby-lvm-attrib gem to 0.3.14
List any existing issues this PR resolves
> Update chef-ruby-lvm-attrib gem to 0.3.14

- CHANGELOG.md
- attributes/default.rb
Update chef-ruby-lvm-attrib gem to 0.3.15
Unable to load lvm attributes [lvs.yaml] for version [2.03.22(2)]
> Update chef-ruby-lvm-attrib gem to 0.3.15
